name: "Backup Helm Charts"

on:
  push: # runs on any branch push
  schedule:
    - cron: "0 0 * * 1" # runs every Monday at midnight
  workflow_dispatch: # runs whenever the workflow is dispatched via the UI

permissions:
  contents: write

jobs:
  download-charts:
    uses: ./.github/workflows/tpl-download-charts.yaml
    with:
      registry-source: "https://charts.konstruct.io/"
