name: "Backup and then Mirror Helm Charts"

on:
  # push: # runs on any branch push
  # schedule:
  #   - cron: "0 0 * * 1" # runs every Monday at midnight
  workflow_dispatch: # runs whenever the workflow is dispatched via the UI

env:
  REGISTRY_SOURCE: "https://charts.konstruct.io/"
  REGISTRY_DESTINATION: "https://charts.konstruct.io/"

permissions:
  contents: write

jobs:
  download-charts:
    uses: ./.github/workflows/tpl-download-charts.yaml
    with:
      registry-source: "https://charts.konstruct.io/"

  mirror-charts:
    uses: ./.github/workflows/tpl-mirror-charts.yaml
    with:
      registry-destination: "https://charts.konstruct.io/"
    secrets: inherit
