name: "Mirror Helm Charts"

on:
  # push: # runs on any branch push
  workflow_dispatch: # runs whenever the workflow is dispatched via the UI

env:
  REGISTRY_DESTINATION: "https://charts.konstruct.io/"

permissions:
  contents: write

jobs:
  mirror-charts:
    uses: konstructio/charts-mirror/.github/workflows/tpl-mirror-charts.yaml@mirror-only
    with:
      registry-destination: "${REGISTRY_DESTINATION}"
