name: "Mirror Helm Charts"

on:
  # push: # runs on any branch push
  workflow_dispatch: # runs whenever the workflow is dispatched via the UI

permissions:
  contents: write

jobs:
  mirror-charts:
    uses: ./.github/workflows/tpl-mirror-charts.yaml
    with:
      registry-destination: "https://charts.konstruct.io/"
